---
title: Test blog 1
timezone: Europe/Brussels
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jbargbant59@gmail.com
description: 'Site test demo 1

'
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
